### ISSUE TITLE
support multiple users on same domain

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#644]
raised by @mblaney in https://github.com/snarfed/bridgy/issues/629#issuecomment-206748584: https://unicyclic.com/ is a multi-user site where users are on paths instead of subdomains, e.g. https://unicyclic.com/mal/ . he'd like bridgy publish to identify him by domain and path, instead of just domain, so that unicyclic.com users can use it but are limited to only publishing posts under their own path, to only their own silo accounts.

we store full web site URLs in [`domain_urls`](https://github.com/snarfed/bridgy/blob/master/models.py#L110), so this is definitely doable. when a publish request comes in, we currently look up the bridgy (silo) account by `domain`, but we could use `domain_url` instead. we wouldn't know which part of the path to use, though, so we'd probably need to look through all accounts on that domain (and silo) and use the one that most narrowly matches the post's path.

if/when we get a lot of users on one domain, we'd need to think of a more scalable way, but this would work fine to start.

**Comment by kylewm** [comment]
Maybe instead of or in addition to "authors can only publish pages under their path", Bridgy could check rel=author/u-author on the permalink.

(that would help with the way Known, and I think Wordpress too, represent multiuser sites)

**Comment by snarfed** [comment]
@kylewm that would (still) allow spoofing if it was the only check, though, right?

**Comment by kylewm** [comment]
True!

**Comment by mblaney** [comment]
hi @snarfed, @kylewm, could you review this for me? https://github.com/mblaney/bridgy/commit/3fc78f3a8017c8d9439d94d4b567faf265010006

If that's ok, then I feel like the harder part is writing a test for it. It looks like I need multiple sources (as in multiple testutil.FakeSource instances), but would love some help to do that. Couldn't see an example in test_publish.py that did anything similar. thanks!

**Comment by snarfed** [comment]
awesome! thank you for the contribution! @kylewm can definitely weigh in too if he wants, but overall this definitely makes sense to me, and i'm pleasantly surprised at how clean and minimal it is. nice work!

re tests, you're right, you'll use multiple `FakeSource`s. you can create more in your test directly, just like the one in `PublishTest.setUp` is created.

otherwise, we'll want to update the docs too, and i have a handful of style nits on the commit, but nothing substantive. thanks again!

btw, was setup ok once you upgraded your distro? were you able to run the tests and dev_appserver? i'm happy to add any new problems to the docs that aren't already there, ie https://github.com/snarfed/bridgy#development and https://github.com/snarfed/oauth-dropins#troubleshootingfaq .

**Comment by kylewm** [comment]
Echoing snarfed's comment, that I'm glad it's such a tidy and incisive change! 

I'm curious how it would handle the situation where `unicyclic.com/mal` has signed up for Bridgy, but `unicyclic.com/kyle` has not. If I post `unicyclic.com/kyle/i-am-a-nerd` and ping Bridgy publish with it, would it publish to mal's Facebook?

**Comment by snarfed** [comment]
great catch! i think it would. the default starting with the first domain match was nagging at me too, but i didn't see why concretely.

so, we probably want to require `startswith(domain_url)`?

bigger picture, beyond this specific issue/PR, if we want to fully support path-based users, we'll need to audit the code and find all the other places we currently assume a domain-per-user mapping. after a few greps, these look likely:

* [models.py:569](https://github.com/snarfed/bridgy/blob/ae49a3260a9b68a4039fe52f722dc3a709e4cbf2/models.py#L569): `   user = self.__class__.query(self.__class__.domains == domain).get()`
* [original_post_discovery.py:72](https://github.com/snarfed/bridgy/blob/ae49a3260a9b68a4039fe52f722dc3a709e4cbf2/original_post_discovery.py#L72): `   activity, domains=source.domains, cache=memcache,`
* [tasks.py:648](https://github.com/snarfed/bridgy/blob/ae49a3260a9b68a4039fe52f722dc3a709e4cbf2/tasks.py#L648): `       util.domain_from_link(mention.target_url) in self.source.domains):`

also, we currently cache webmention endpoint by domain, which people (eg @aaronpk) have said before is technically an overreach. @mblaney, how do unicyclic.com's wm endpoint(s) work?

**Comment by mblaney** [comment]
thanks for all the feedback! I wasn't expecting you to merge as-is, so I'm happy to keep working on it. Sorry if I'm missing something, but would multiple `FakeSource`s look like:
`publish.SOURCE_NAMES['fake'] = {testutil.FakeSource1, testutil.FakeSource2}`?

To answer everything else: yes after the distro upgrade everything worked perfectly. no documentation updates needed :-) I don't even know what dev_appserver is, but I'm guessing it worked because I didn't get any errors...

@kylewm thanks yes that's a good one (though it's also how bridgy currently works for me!). I left the first match in there because there are some tests where url doesn't match domain_urls at all, but I think I need to go through each of them and work out how to include them.

I have one webmention endpoint for the whole domain, the relevant user is extracted from the path provided. (So that's at least not another problem at the moment.) Will look into adding the other changes suggested.

**Comment by snarfed** [comment]
hey, you're welcome, thanks again for the contribution!

> Sorry if I'm missing something, but would multiple FakeSources look like:
publish.SOURCE_NAMES['fake'] = {testutil.FakeSource1, testutil.FakeSource2}?

close! you'd actually just create and store new instances, like these lines: https://github.com/snarfed/bridgy/blob/ae49a3260a9b68a4039fe52f722dc3a709e4cbf2/test/test_publish.py#L36-39

> To answer everything else: yes after the distro upgrade everything worked perfectly. no documentation updates needed :-) I don't even know what dev_appserver is, but I'm guessing it worked because I didn't get any errors...

great! dev_appserver is a self-contained web server from the SDK that lets you run and use the app on localhost. https://cloud.google.com/appengine/docs/python/tools/devserver

**Comment by mblaney** [comment]
aaah thanks I didn't realize you could just keep calling push() to add sources. So I've done that and it gets me a bit further, but what I'm hitting now is that I want an `assertEquals` on matching the location header. The problem I have is that it's always set to http://fake/url, whereas I want my second account on the same domain to have a different fake url to publish to.

It looks like I should be able to set a url in `FakeSource.new()`, but I think `FakeGrSource.create()` is overriding it? The url there is also hard coded to http://fake/url. Again would be happy to find that I've missed something and that there's an easier way to add this test.

**Comment by snarfed** [comment]
you're right, `FakeGrSource` definitely does hard code `http://fake/url`. if you want to change that for each source, you could make `FakeGrSource` pull it from a class attribute instead, say `published_url`, and set each `source.gr_source.published_url` in your test to something different. or you could mock out the `gr_source.create(...)` calls entirely, like other tests in `test_publish` do, but that's probably overkill.

**Comment by mblaney** [comment]
it looks to me like `FakeSource` instances share the same `FakeGrSource`? So I've added published_url class attribute, but only the value that it was last set to gets used. I've then tried to mock `gr_source.create`, but I really need multiple instances so that `publish.py` is forced to choose the closer match. Any ideas how I could do that?

**Comment by mblaney** [comment]
also here's an updated version of the change, taking everything discussed so far into account: https://github.com/mblaney/bridgy/commit/336e397f272dcbb313e4c8e304f61f121f9fb23d

I'm pretty sure it fixes the case @kylewm mentioned, though I would like to add a test for it (once I've worked out how to do that...) I also think this version picks up a bug in a test that I've modified, depends on your stance on http/https being the same url when the scheme is the only difference.

**Comment by snarfed** [comment]
thanks for the update! new code looks good, and agreed, it should fix the bug kyle mentioned.

and you're right, we do generally consider http vs https equivalent when scheme is the only difference, and afaik W3C does too, but i don't feel strongly. if you want to preserve that, you could use `util.update_scheme` or `UrlCanonicalizer` before comparing against `domain_url`.

and sorry the test and fake classes are so difficult! you're right, they definitely weren't designed to change the response that `create` returns.

are you hoping to use the `url` field in the response to distinguish between sources? you might consider just checking something different altogether. if you get the `Publish` entity that gets stored in the datastore, its `source` field should work, right?

**Comment by mblaney** [comment]
thanks for the hint about `Publish`! I should've noticed how that was being used, was definitely making it hard for myself :-)

**Comment by snarfed** [comment]
woo, this is live! feel free to try it out @mblaney. you're welcome to close this if it works!

**Comment by mblaney** [comment]
yay it works! :-D

There is still an issue with publish.py leaking information, I posted from unicyclic.com/test and got the error message: "Publish is not enabled for your account(s). Please visit https://brid.gy/twitter/malcolmblaney and sign up!". Will close this though and create another issue, any ideas on how to provide a more helpful error message?

**Comment by mblaney** [comment]
oh I can't close this issue as I didn't create it.
